# -*- coding: utf-8 -*-
"""tesla.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XjrlBoq9xxH6IoioMNIqi7qq9t2ExkR
"""

import pandas as pd
import seaborn as sns
import yfinance as yf
import matplotlib.pyplot as plt

"""Setting the symbol reqired for Yf API (You can find it in yahoo finance website)"""

ticker_symbol = "TSLA"

"""selecting the start and end dates for a perticuler stock

"""

start_date = "2021-01-01"
end_date = "2022-12-31"

"""Getting stock data with YF API"""

get_stock_data = yf.download(ticker_symbol, start=start_date, end=end_date)

"""Storing stock data in Panda dataframe

"""

stock_data = pd.DataFrame(get_stock_data)
stock_data

#resetting the index
stock_data.reset_index(inplace=True)

"""Showing data with sns and matplotlib library """

sns.set(style="darkgrid")
sns.lineplot(data=stock_data, x="Date", y="Close")
plt.figure(figsize=(26, 20))
plt.show()

